#
# This software may be modified and distributed under the terms
# of the MIT license.  See the LICENSE file for details.

name: CI Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Python ${{ matrix.python }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python: ['3.8', '3.9', '3.10', '3.11', '3.12']
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Update Pip
        run: pip install --upgrade pip setuptools

      - name: Install Tox
        run: pip install tox

      - name: Run tests
        run: tox -e py
